# Generated by Django 6.0 on 2025-12-12 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_class', models.CharField(choices=[('marshall', 'Marshall'), ('gunslinger', 'Gunslinger'), ('rancher', 'Rancher')], max_length=50)),
                ('agility', models.IntegerField(default=0)),
                ('cunning', models.IntegerField(default=0)),
                ('spirit', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('lore', models.IntegerField(default=0)),
                ('luck', models.IntegerField(default=0)),
                ('combat', models.IntegerField(default=0)),
                ('max_grit', models.IntegerField(default=0)),
                ('grit', models.IntegerField(default=0)),
                ('range', models.IntegerField(default=0)),
                ('melee', models.IntegerField(default=0)),
                ('initiative', models.IntegerField(default=0)),
                ('max_health', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('armor', models.IntegerField(default=0)),
                ('max_sanity', models.IntegerField(default=0)),
                ('sanity', models.IntegerField(default=0)),
                ('will_power', models.IntegerField(default=0)),
                ('spirit_armor', models.IntegerField(default=0)),
                ('max_horror', models.IntegerField(default=0)),
                ('horror', models.IntegerField(default=0)),
                ('corruption_resistance', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
