# Generated by Django 6.0 on 2025-12-16 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='abilities',
            field=models.ManyToManyField(blank=True, to='characters.ability'),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='current_ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_characters', to='characters.ability'),
        ),
    ]
