# Generated by Django 6.0 on 2025-12-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_ability_charactersheet_abilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='name',
            field=models.CharField(blank=True, default='Unnamed Hero', max_length=100),
        ),
    ]
