# Generated by Django 6.0 on 2025-12-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_classability_charactersheet_class_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='dark_stone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
