# Generated by Django 6.0 on 2025-12-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_charactersheet_dark_stone_charactersheet_gold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaddleBagToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='tokens',
            field=models.ManyToManyField(blank=True, to='characters.saddlebagtoken'),
        ),
    ]
