# Generated by Django 6.0 on 2025-12-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_saddlebagtoken_charactersheet_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactersheet',
            name='tokens',
        ),
    ]
