# Generated by Django 6.0 on 2025-12-24 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_remove_charactersheet_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='characters.charactersheet')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.saddlebagtoken')),
            ],
        ),
    ]
