# Generated by Django 6.0 on 2025-12-24 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_charactertoken'),
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactertoken',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.saddlebagtoken'),
        ),
        migrations.DeleteModel(
            name='SaddleBagToken',
        ),
    ]
