# Generated by Django 6.0 on 2025-12-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_alter_charactertoken_token_delete_saddlebagtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactersheet',
            name='class_ability',
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='class_abilities',
            field=models.ManyToManyField(blank=True, to='characters.classability'),
        ),
    ]
