# Generated by Django 6.0 on 2026-01-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_remove_charactersheet_class_ability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='calculated_health',
            field=models.FloatField(default=0),
        ),
    ]
