# Generated by Django 6.0 on 2026-01-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_charactersheet_calculated_health'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charactersheet',
            old_name='horror',
            new_name='corruption',
        ),
        migrations.RenameField(
            model_name='charactersheet',
            old_name='max_horror',
            new_name='max_corruption',
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='calculated_corruption',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='calculated_sanity',
            field=models.FloatField(default=0),
        ),
    ]
