# Generated by Django 6.0 on 2026-01-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_rename_horror_charactersheet_corruption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='calculated_grit',
            field=models.FloatField(default=0),
        ),
    ]
